M48
; DRILL file {KiCad 9.0.6} date 2025-11-07T09:00:52+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-07T09:00:52+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X5.48Y12.89
X5.48Y7.11
T2
X30.199Y18.205
X30.199Y1.782
X33.199Y18.205
X33.199Y1.782
T3
X2.0Y18.0
X2.0Y2.0
M30
