M48
; DRILL file {KiCad 9.0.1} date 2025-04-09T10:04:17+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-09T10:04:17+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X5.48Y12.89
X5.48Y7.11
T2
X24.845Y18.255
X27.845Y18.255
T3
X2.0Y18.0
X2.0Y2.0
M30
